@UsersMicroservice_HostAddress = http://localhost:5046

//POST {{UsersMicroservice_HostAddress}}/api/Users
POST https://localhost:7106/api/Users/eeMacarena
Accept: */*

{
# "Email": "yo@gmail.com",
  "Email": "paco@gmail.com",
  "Password": "aA1_bB2$cC3"
}
###
