@UsersMicroservice_HostAddress = https://localhost:7106
@pk = f4629418-7a7e-471b-886d-330a3e9b42b6
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkYXZpZC5sbG9waXNsYWd1bmFAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiZWQ3ZjdjMmMtZWVkNS00MmQyLTllMmMtMTNjZWQzODY3N2IzIiwiZXhwIjoxNzA2OTY3MTcwLCJpc3MiOiJGYWN0aXZhciIsImF1ZCI6IkZhY3RpdmFyIn0.Llx8o61oXSp2pUCitboy0Zlr_7i7yFrAZSDubo-Om98

### usuariosMS/api/Users
GET {{UsersMicroservice_HostAddress}}/api/Users HTTP/1.1
Content-Type: text/plain
# www-authenticate: Bearer
Authorization: Bearer {{token}}

""
### usuariosMS/api/Users/{pk}
GET {{UsersMicroservice_HostAddress}}/api/Users/{{pk}} HTTP/1.1
Content-Type: text/plain
Authorization: Bearer {{token}}

""
###

POST {{UsersMicroservice_HostAddress}}/register
Content-Type: application/json

{
  "Nombre": "Admin",
  "Apellidos": "Factivar Web",
  "Telefono":"685107027",
  "Email": "factivaradm@gmail.com",
  "Password": "#HazteUnPaco69$"
}
###

POST {{UsersMicroservice_HostAddress}}/login
Content-Type: application/json

{
# "Email": "factivaradm@gmail.com",
# "Password": "#HazteUnPaco69$"
 "Email": "david.llopislaguna@gmail.com",
 "Password": "$passwordSeguro&0"
}
###