@Ocelot_API_Gateway_HostAddress = https://localhost:7230
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTaWQiOiJhZWI3NTc4NC1lZjNjLTQyNWMtODRiZC1hMDk2N2FmNjIwNWYiLCJFbWFpbCI6ImZhY3RpdmFyYWRtQGdtYWlsLmNvbSIsIk5hbWUiOiJBZG1pbmlzdHJhZG9yIiwiU3VybmFtZSI6IkZhY3RpdmFyIFdlYiIsIlJvbGUiOiJBZG1pbiIsIlRodW1icHJpbnQiOiJDOi9EZXYvLk5FVC9GYWN0aXZhclByb2plY3QvQXV0aE1TL3d3d3Jvb3QvSW1hZ2VzLzJhMmU4Nzk0LWEwYjUtNDhjYi05NTk1LWI2ODgwOTg3MGNhOV9pbWFnZV9wbmcucG5nIiwiZXhwIjoxNzA5MzMxNTQ0LCJpc3MiOiJGYWN0aXZhciIsImF1ZCI6IkZhY3RpdmFyIn0.xeSWqpKvbAdM1WyRlRtzPmriNMIOfOk37i9kn5i00DY
@pk = 55234902D
@fechamin = 2023-01-01
@fechamax = 2024-01-30

GET {{Ocelot_API_Gateway_HostAddress}}/api/clientes/all
Content-Type: text/plain
Authorization: Bearer {{token}}

""
###

GET {{Ocelot_API_Gateway_HostAddress}}/api/clientes/{{pk}}
Content-Type: text/plain
Authorization: Bearer {{token}}

""
###

GET {{Ocelot_API_Gateway_HostAddress}}/api/clientes/alta-entre-fechas/{{fechamin}}/{{fechamax}}
Content-Type: text/plain
Authorization: Bearer {{token}}

""
###

POST {{Ocelot_API_Gateway_HostAddress}}/api/clientes
Content-Type: application/json
Authorization: Bearer {{token}}

# {
#   "cif": "55234902D",
#   "nombre": "Paco",
#   "direccion": "Carchelejo",
#   "telefono": 655872010,
#   "email": "paco@gmail.com",
#   "fechaAlta": "2024-01-15"
# }
{
  "cif": "b23425374",
  "nombre": "manuel",
  "direccion": "la de bob esponja",
  "telefono": 123456789,
  "email": "manuelcarreto@hotmail.com",
  "fechaAlta": "2024-02-01"
}
###

PUT {{Ocelot_API_Gateway_HostAddress}}/api/clientes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cif": "55234902D",
  "nombre": "Paco",
  "direccion": "Carchelejo",
  "telefono": 655872010,
  "email": "paco@yahoo.com",
  "fechaAlta": "2024-01-15"
}

###

DELETE {{Ocelot_API_Gateway_HostAddress}}/api/clientes/{{pk}}
Content-Type: text/plain
Authorization: Bearer {{token}}

""
###