@Ocelot_API_Gateway_HostAddress = https://localhost:7230
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ1c3VhcmlvQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYjI3NjJiYzgtNjQxNi00OWJjLWE4YTAtNDUyNjJiNmIxODkzIiwiZXhwIjoxNzA2NTQxMzg1LCJpc3MiOiJGYWN0aXZhciIsImF1ZCI6IkZhY3RpdmFyIn0.P7LOl6zIny3H2-xq_RSjnyxEZqequ06m2sRacaliUHY
@pk_fatura = 6
@pk_cliente = 6
@month = 1
@trimestre = 1
@year = 2024

GET {{Ocelot_API_Gateway_HostAddress}}/api/facturas/{{pk_fatura}}
Content-Type: text/plain
Authorization: Bearer {{token}}

""
###

GET {{Ocelot_API_Gateway_HostAddress}}/api/facturas/iva/mensual/{{pk_cliente}}/{{month}}/{{year}}
Content-Type: text/plain
Authorization: Bearer {{token}}

""
###

GET {{Ocelot_API_Gateway_HostAddress}}/api/facturas/iva/trimestral/{{pk_cliente}}/{{trimestre}}/{{year}}
Content-Type: text/plain
Authorization: Bearer {{token}}

""
###

GET {{Ocelot_API_Gateway_HostAddress}}/api/facturas/iva/anual/{{pk_cliente}}/{{year}}
Content-Type: text/plain
Authorization: Bearer {{token}}

""
###

GET {{Ocelot_API_Gateway_HostAddress}}/api/facturas/pendientes-pago/{{pk_cliente}}
Content-Type: text/plain
Authorization: Bearer {{token}}

""
###

POST {{Ocelot_API_Gateway_HostAddress}}/api/facturas
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "numeroFactura": 1,
  "pendientePago": false,
  "descripcionOperacion": "pruebapalllopis",
  "fechaExpedicion": "2024-01-15",
  "fechaCobro": "2024-01-15",
  "clienteId": "55234902D",
  "proveedorId": "73657861Q",
  "articulos": [
  	{
    	  "descripcion": "p1",
    	  "unidades": 1,
    	  "pUnitario": 10,
    	  "iva": 0
  	},
	{
    	  "descripcion": "p2",
    	  "unidades": 2,
    	  "pUnitario": 2,
    	  "iva": 10
  	},
	{
    	  "descripcion": "p3",
    	  "unidades": 3,
    	  "pUnitario": 3,
    	  "iva": 21
  	}
  ]
}

###

